from . import boq
from . import boq_line
from . import boq_sub_item
from . import variation_order
from . import cost_details_line_inherit
from . import res_partner_inherit
from . import material_purchase_requisition_inherit
from . import purchase_requisition_inherit
from . import ipc_certificate
from . import account_move_inherit
from . import purchase_order_inherit
from . import account_tax_group
