{
    'name': 'Bill Of Quantity Management for Construction',
    'version': '1.0',
    'summary': 'Digital Projecta for Construction Management Spicially in Bill Of Quantity Phase',
    'description': """ """,
    "license": "LGPL-3",
    'author': 'Dgprojx',
    'depends': ['base', 'mail', 'dg_estimation', 'purchase', 'cr_material_purchase_requisitions'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'reports/boq.xml',
        'reports/ipc.xml',
        'views/boq_view.xml',
        'views/boq_sub_item_view.xml',
        'views/variation_order_view.xml',
        'views/res_partner_inherit_view.xml',
        'views/purchase_requisition_inherit.xml',
        'views/ipc_certificate.xml',
        'views/account_move_inherit.xml',
        'views/material_purchase_requisition_form_view_inherit.xml',
        'views/purchase_order_form_view_inherit.xml',
        'views/account_tax_group_form_view_inherit.xml',
        'wizards/subcontractor_request_view.xml',
        'views/menus.xml',
    ],

    'demo': [],
    'installable': True,
    'application': True,
}
